#Database
POSTGRESQL_USERNAME: admin
POSTGRESQL_PASSWORD: admin
POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: securedoc

#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: http://localhost:8085
EMAIL_PORT: 587
EMAIL_ID: ssksudhakar.s@gmail.com  # Replace with actual email
EMAIL_PASSWORD: jvwc tupt hoyg lygj     # Replace with actual password
VERIFY_EMAIL_HOST: http://localhost:8085
